# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[[main]]
  name = "Home"
  url = "#demo_home"
  weight = 5
  
[[main]]
  name = "About Us"
  url = "#about"
  weight = 10


[[main]]
  name = "Events"
  url = "#talks"
  weight = 20
  
[[main]]
  name = "Blog"
  url = "#posts"
  weight = 30

  
[[main]]
  name = "Get Involved"
  url = "#projects"
  weight = 40

#[[main]]
#  name = "R-Ladies Global"
#  url = "https://rladies.org/about-us/"
#  weight = 50
  
[[main]]
  name = "Gallery"
  url = "#gallery"
  weight = 55
  
[[main]]
  name = "Board"
  url = "#Board"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
